controller_joint_names: ['', 'base2_joint', 'shoulder2elbow1_joint', 'elboe2twist1_joint', 'Gripper1_joint', 'Gripper4.1_joint', 'Gripper4.2_joint', 'shoulder2elbow2.2_joint', 'elbow2twist2.2_joint', ]
